### PR TITLE
Upgrade package for react-0.14.0, use findDOMNode

### PR DESCRIPTION
**Pull request by kumarharsh**
This PR addresses the points raised in #77

### CODE REVIEW

**Comment by okonet** [comment]
This looks good. Can you please remove version bump from it? I'll do it myself. Thanks!

**Comment by kumarharsh** [comment]
Alright

**Comment by kumarharsh** [comment]
Although there should be another commit on the 2.x branch, which changes the dep from

`"react": ">=0.13"`

to 
`"react": "^0.13"`

or something similar, because although the 2.x branch does work with 0.14 as of now, things may change later, and the `>=` does not offer any guarantee of compatibility whatsoever.

**Comment by okonet** [comment]
Yeah. I can take care of it

**Pull request merged**
