### PR TITLE
Hidden input[type=file] should have name attribute

### PR DESCRIPTION
**Pull request by nickhudkins**
This will allow react-dropzone to work onClick with standard browser POSTs. addresses conflicts in #30

### CODE REVIEW

**Comment by paramaggarwal** [comment]
@nickhudkins But the component does not have a <form> wrapper around the <input> which means that simple browser form post anyways does not work.

**Comment by nickhudkins** [comment]
True... so... I guess I am confused what you intended the use of this library to be. 

As I see it it is an enhanced file input field, which could be used in a <form> and in that case, the name attribute is important.

I guess my largest question for you is, what is the disadvantage of treating this as a semantic file input at it's core, and the additional functionality being just that, additional.

**Comment by paramaggarwal** [comment]
@nickhudkins The library is intended to be used as a drag and drop component. There is no clean way to make this work as a simple `input` field. I'll see if the dropped file can be set as the file on the `input` field itself. As if it was selected from the dropdown - then it would be pretty cool.

**Comment by paramaggarwal** [comment]
Closing as the primary feature of the library is drag and drop, and the `input` field is only to allow selection by clicking. To use with regular form POSTs, please directly use your own `input` field.

**Pull request closed without merging**
