### PR TITLE
Adding option to make dropzone transparent

### PR DESCRIPTION
**Pull request by Sapphire64**
I wanted to use dropzone component as an transparent wrapper with high-level files API around my components, in this usage case I don't really need to have that styles and rewriting styles option with dummy data looks wrong to me.

What do you think about having this option?

### CODE REVIEW

**Comment by paramaggarwal** [comment]
Just saying `style={{}}` seems fine.

**Comment by Sapphire64** [comment]
@paramaggarwal But to know that it makes any effect you need to check sources. Maybe we should at least mention it somewhere?

**Comment by paramaggarwal** [comment]
Very true! I'll do that once I find some time. :)

**Comment by Sapphire64** [comment]
Ok, closing this one :)

**Comment by paramaggarwal** [comment]
No no, leave it open as an open task to complete!

**Comment by paramaggarwal** [comment]
Resolved via https://github.com/paramaggarwal/react-dropzone/pull/46

**Pull request closed without merging**
