### PR TITLE
Use default styles and merge in user set ones

### PR DESCRIPTION
**Pull request by ravloony**
Hi,

I propose a patch to allow users to set one or more styles, without losing all the other defaults.

This is because I want to have the dropzone have an automatic width, by setting {width: '100%'} without losing the dashed border which becomes solid on dragging a file.

My code is a little verbose, but should work anywhere.

Thanks.

### CODE REVIEW

**Comment by paramaggarwal** [comment]
How about expose `this.state.isDragActive` instead in some way?

**Comment by ravloony** [comment]
Thanks for the reply!

How about a dragActiveStyle prop which would apply only when this.state.isDragActive is true?

**Comment by paramaggarwal** [comment]
Too complex, simplest pattern is of the component to send stuff up to the parent via callbacks and then the parent can send updated props like `style` to the component.

**Comment by paramaggarwal** [comment]
Please use the `onDragOver` and `onDragLeave` prop function that you can pass - this is how the border setting is done internally - https://github.com/paramaggarwal/react-dropzone/blob/master/index.js#L33-L60

**Comment by ravloony** [comment]
Isn't that two way data flow? I'd say it's cleaner for the component to manage it's own state, rather than asking the parent to update a prop on an event. If the parent is always going to update the style when the drag happens, then why not put that logic in the component itself?

**Comment by paramaggarwal** [comment]
My main concern is that this change brings more switches and controls to an otherwise simple component. Hence against the idea of adding more `props`.

Also the React pattern is to have stateless components, pass data down using props, pass events up using callbacks and maintain as much state as possible at the very top level.

**Comment by ravloony** [comment]
Ok, fair enough! Thanks for your time!

**Comment by paramaggarwal** [comment]
Thanks for understanding. Also with this PR, there would not have been a way to override the default styling then.

**Pull request closed without merging**
